Revert "Remove unnecessary struts-html.tld, struts-logic.tld and struts-tils.tld from intermine-webapp"
For some reason, it appears these are still required, as removal results in errors such as

org.apache.jasper.JasperException: Unable to find taglib "html" for URI: /WEB-INF/struts-html.tld

This reverts commit 4c982a8213a8b3b093d1ac7a3d27caf81651d2f2.